version: '3'

services:
    django_app:
        build:
            context: .
            dockerfile: Dockerfile
        command:
            gunicorn isteam.wsgi:application --bind 0.0.0.0:8000
        ports:
            - '8000'
        env_file: 
            - '.prod.env'
        container_name: django_app
    
    nginx_web:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - './nginx.conf:/etc/nginx/nginx.conf'